import type {Event,EventType,EventStatus,LifeOSBackup,LifeOSDatabase,Relationship,RelationshipType} from "@/domain/contracts/database";

type R=Record<string,any>;
const SCHEMA_VERSION="2.1.0";
const APP_VERSION="0.2.0";
export const IMMUTABLE_SEED_VERSION="FLC-v5-d22e0386087b4d6e";
const nowIso=()=>new Date().toISOString();
const iso=(v:any, fallback:string)=>{if(typeof v==="number")return new Date(v).toISOString();if(typeof v==="string"&&v)return v.length===10?v+"T00:00:00.000Z":v;return fallback};
const money=(v:any)=>typeof v==="number"?Math.round(v*100):0;
const base=(id:string,type:string,created:any,updated:any,metadata:R={})=>({id,entityType:type,createdAt:iso(created,nowIso()),updatedAt:iso(updated,nowIso()),metadata});
const eventType=(v:any):EventType=>({task:"task",meeting:"meeting",conversation:"conversation",appointment:"appointment",purchase:"purchase",payment:"payment",income:"income",expense:"expense",transfer:"transfer",maintenance:"maintenance",repair:"repair",inspection:"inspection",travel:"travel",decision:"decision",observation:"observation",milestone:"milestone",document:"document",communication:"communication",workout:"workout",learning:"learning","Doctor Visit":"appointment","Workout":"workout","Maintenance":"maintenance","Learning Session":"learning","Vacation":"travel","Planning":"task","Work":"task","Relationship":"conversation","Conversation":"conversation","Meeting":"meeting","Purchase":"purchase",system:"observation"}[v]??"other");
const status=(v:any):EventStatus=>({Completed:"completed",completed:"completed",Planned:"planned",planned:"planned",Scheduled:"scheduled",InProgress:"in_progress","In Progress":"in_progress",Cancelled:"cancelled",cancelled:"cancelled"}[v]??"planned");
const loopStatus=(v:any):"open"|"in_progress"|"waiting"|"blocked"|"resolved"|"cancelled"=>({open:"open",Open:"open",active:"in_progress",Active:"in_progress",complete:"resolved",Completed:"resolved",resolved:"resolved",waiting:"waiting",Waiting:"waiting",blocked:"blocked",Blocked:"blocked"}[v]??"open");
const priority=(v:any):"low"|"normal"|"high"|"critical"|undefined=>({Low:"low",low:"low",Medium:"normal",medium:"normal",High:"high",high:"high",Critical:"critical",critical:"critical"}[v] as any);
const goalLevel=(v:any):"annual"|"quarterly"|"monthly"|"weekly"=>String(v??"weekly").toLowerCase() as any;
const relationType=(v:any):RelationshipType=>v==="vehicle"?"uses":"linked_to";
const vehicleParts=(name:string)=>{const m=name.match(/^(\\d{4})\\s+(.+)$/);const rest=m?.[2]??name;const parts=rest.split(" ");return{year:m?Number(m[1]):undefined,make:parts[0]??"Unknown",model:parts.slice(1).join(" ")||"Unknown"}};
const uniqueId=(id:any,prefix:string)=>String(id).startsWith(prefix)?String(id):prefix+String(id);

export function normalizeLegacySeed(source:unknown):LifeOSBackup{
 const s=source as R;
 const created=iso(s._exportedAt,nowIso());
 const events:Event[]=[];
 for(const x of (s.events??[]) as R[]){
  const people=x.personIds??x.people??[]; const goals=x.goalIds??x.goals??[];
  events.push({...base(String(x.id),"event",x.createdAt,x.updatedAt,{legacy:{source:"events",record:{...x}}}),eventType:eventType(x.type),title:String(x.title??"Untitled"),description:x.notes||undefined,status:status(x.status),occurredAt:iso(x.date,created),dueAt:x.dueDate?iso(x.dueDate,created):undefined,personIds:people.map(String),goalIds:goals.map(String),source:"Full Life Control FLC-v5"});
 }
 const people=(s.people??[] as R[]).map(x=>({...base(String(x.id),"person",x.createdAt,x.updatedAt,{legacy:{source:"people",record:{...x}}}),firstName:String(x.name??"").split(" ")[0]??"",lastName:String(x.name??"").split(" ").slice(1).join(" ")||undefined,displayName:String(x.name??""),notes:x.notes||x.relationship||undefined}));
 const assets=(s.assets??[] as R[]).map(x=>({...base(String(x.id),"asset",x.createdAt,x.updatedAt,{legacy:{source:"assets",record:{...x}},value:x.value,debt:x.debt}),assetType:String(x.category??x.type??"other").toLowerCase().includes("vehicle")?"vehicle":String(x.category??x.type??"other").toLowerCase().includes("invest")?"investment":String(x.category??x.type??"other").toLowerCase().includes("property")?"property":String(x.category??x.type??"other").toLowerCase().includes("cash")?"cash":"other",name:String(x.name??"Unnamed"),description:x.notes,currency:"USD"}));
 const accounts=(s.accounts??[] as R[]).map(x=>{const t=String(x.type??"").toLowerCase();const n=String(x.name??"").toLowerCase();const accountType=t.includes("debt")||n.includes("credit")?"credit_card":n.includes("saving")?"savings":n.includes("cash")?"cash":n.includes("invest")?"investment":"checking";return {...base(String(x.id),"financial_account",x.createdAt,x.updatedAt,{legacy:{source:"accounts",record:{...x}},startingBalance:x.startingBalance,balance:x.balance}),name:String(x.name??"Account"),accountType,currency:"USD",openingBalanceMinor:money(x.startingBalance??x.balance??0)}});
 const accountByName=new Map(accounts.map(x=>[x.name.toLowerCase(),x.id]));
 const txAccountNames=new Set<string>();
 for(const x of (s.transactions??[]) as R[])if(x.account)txAccountNames.add(String(x.account));
 for(const name of txAccountNames)if(!accountByName.has(name.toLowerCase())){const id="legacy-account-"+name.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");accounts.push({...base(id,"financial_account",created,created,{legacy:{source:"transactions.account",accountName:name}}),name,currency:"USD",accountType:"checking"});accountByName.set(name.toLowerCase(),id)}
 const transactions=(s.transactions??[] as R[]).map(x=>({...base(String(x.id),"financial_transaction",x.createdAt,x.updatedAt,{legacy:{source:"transactions",record:{...x}}}),transactionType:"expense" as const,transactionDate:String(x.date),amountMinor:money(Math.abs(Number(x.amount??0))),currency:"USD",accountId:accountByName.get(String(x.account??"").toLowerCase())??accounts[0]?.id??"legacy-account-default",merchant:x.merchant,description:x.notes,metadata:{legacyCategory:x.category,paycheckWindow:x.paycheckWindow,importedFrom:x.importedFrom}}));
 const vehicles:any[]=[];
 const vehicleAssetIds=new Set<string>(assets.map(x=>x.id));
 for(const x of (s.vehicles??[]) as R[]){const id=String(x.id);const parts=vehicleParts(String(x.name??id));const assetId="vehicle-asset-"+id;if(!vehicleAssetIds.has(assetId)){assets.push({...base(assetId,"asset",x.createdAt,x.updatedAt,{legacy:{source:"vehicles",record:{...x}}}),assetType:"vehicle",name:String(x.name??id),currency:"USD"});vehicleAssetIds.add(assetId)}vehicles.push({...base(id,"vehicle",x.createdAt,x.updatedAt,{legacy:{source:"vehicles",record:{...x}}}),assetId,year:parts.year,make:parts.make,model:parts.model,currentMileage:Number(x.odometer??0),mileageUnit:"mi",status:"owned",metadata:{engine:x.engine,oilType:x.oilType,oilCapacity:x.oilCapacity,batteryGroup:x.batteryGroup,tireSize:x.tireSize,oilFilter:x.oilFilter,airFilter:x.airFilter,sparkPlugs:x.sparkPlugs,wiperBlades:x.wiperBlades}})}
 const maintenance:any[]=[];
 for(const x of (s.maintenance??[]) as R[]){const original=String(x.id);const id=original==="1"||original==="2"?"maintenance-"+original:original;const eventId="maintenance-event-"+id;const vehicleId=String(x.vehicle);events.push({...base(eventId,"event",x.createdAt,x.updatedAt,{legacy:{source:"maintenance",record:{...x}}}),eventType:"maintenance",title:String(x.serviceType??"Vehicle maintenance"),description:x.notes, status:"completed",occurredAt:iso(x.date,created),assetIds:[vehicleId],source:"Full Life Control FLC-v5"});maintenance.push({...base(id,"vehicle_maintenance",x.createdAt,x.updatedAt,{legacy:{source:"maintenance",record:{...x}}}),vehicleId,eventId,date:String(x.date),mileage:x.mileage!==undefined?Number(x.mileage):undefined,serviceType:String(x.serviceType??"Maintenance"),description:x.notes,vendor:x.notes?.match(/^Provider:\\s*(.+)$/)?.[1],costMinor:money(x.cost??0),currency:"USD"});}
 const projects=(s.projects??[] as R[]).map(x=>{const id=String(x.id);const st=String(x.status??"").toLowerCase();const projectStatus=st.includes("progress")?"active":st==="planned"?"planned":Number(x.completion??0)>=100?"completed":Number(x.completion??0)>0?"active":"planned";return {...base(id,"project",x.createdAt,x.updatedAt,{legacy:{source:"projects",record:{...x}}}),name:String(x.title??"Project"),description:x.category,status:projectStatus,startDate:x.createdAt?iso(x.createdAt,created).slice(0,10):undefined,targetDate:x.dueDate,metadata:{budget:x.budget,actualCost:x.actualCost,completion:x.completion,tasks:x.tasks,priority:x.priority,vehicleId:x.vehicleId}}});
 const goals=(s.goals??[] as R[]).map(x=>({...base(String(x.id),"goal",x.createdAt,x.updatedAt,{legacy:{source:"goals",record:{...x}}}),name:String(x.title??x.name??"Goal"),level:goalLevel(x.level),status:Number(x.progress??0)>=100?"completed":"active",parentGoalId:x.parentId?String(x.parentId):undefined,currentValue:Number(x.progress??0),unit:"percent",metadata:{progress:Number(x.progress??0)}}));
 const openLoops=(s.loops??[] as R[]).map(x=>({...base(String(x.id),"open_loop",x.createdAt,x.updatedAt,{legacy:{source:"loops",record:{...x}}}),title:String(x.title??"Open loop"),description:x.notes,type:String(x.type??"").toLowerCase().includes("decision")?"decision":"task",status:loopStatus(x.status),priority:priority(x.priority),dueAt:x.dueDate?iso(x.dueDate,created):undefined,relatedEventIds:[...(x.eventIds??[]),...(x.eventId?[x.eventId]:[])].map(String)}));
 const decisions=(s.decisions??[] as R[]).map(x=>({...base(String(x.id),"decision",x.createdAt,x.updatedAt,{legacy:{source:"decisions",record:{...x}}}),question:String(x.title??"Decision"),context:x.context,decidedAt:x.createdAt?iso(x.createdAt,created).slice(0,10):undefined,reviewDate:x.reviewDate,outcome:x.actualOutcome||x.expectedOutcome,metadata:{expectedOutcome:x.expectedOutcome,confidence:x.confidence,risk:x.risk,lessons:x.lessons,reviewed:x.reviewed}}));
 const documents:any[]=[];
 const recurringRules:any[]=[];
 const billEvents:Event[]=[];
 const billLoops:any[]=[];
 const billPayments:any[]=[];
 const billPaymentEvents:Event[]=[];
 const billAccountId="legacy-account-bill-payments";
 if(!accounts.some(x=>x.id===billAccountId))accounts.push({...base(billAccountId,"financial_account",created,created,{legacy:{source:"bill-payment-history"}}),name:"Legacy Bill Payments",currency:"USD",accountType:"checking"});
 for(const b of (s.bills??[]) as R[]){
  const id=String(b.id);const eventId="bill-event-"+id;const paid=Number(b.remainingBalance??0)<=0;
  billEvents.push({...base(eventId,"event",b.createdAt,b.updatedAt,{legacy:{source:"bills",record:{...b}}}),eventType:"payment",title:String(b.title??"Bill"),description:String(b.payee??""),status:paid?"completed":"planned",occurredAt:iso(b.dueDate,created),dueAt:iso(b.dueDate,created),source:"Full Life Control FLC-v5"});
  if(!paid)billLoops.push({...base("bill-loop-"+id,"open_loop",b.createdAt,b.updatedAt,{legacy:{source:"bills",record:{...b}}}),title:"Pay: "+String(b.title??"Bill"),description:String(b.payee??""),type:"task",status:"open",priority:"normal",dueAt:iso(b.dueDate,created)});
  if(b.isRecurring)recurringRules.push({...base("recurring-"+id,"recurring_rule",b.createdAt,b.updatedAt,{legacy:{source:"bills",record:{...b}}}),name:String(b.title??"Recurring bill"),eventType:"payment",frequency:"monthly",startDate:String(b.createdAt??created).slice(0,10),enabled:true,template:{billId:id,payee:b.payee,originalBalance:b.originalBalance,remainingBalance:b.remainingBalance,category:b.category,dueDate:b.dueDate}});
  for(const p of (b.paymentHistory??[]) as R[]){const txId="bill-payment-tx-"+id+"-"+String(p.date).replace(/[^0-9]/g,"");const evId="bill-payment-event-"+id+"-"+String(p.date).replace(/[^0-9]/g,"");transactions.push({...base(txId,"financial_transaction",p.date,p.date,{legacy:{source:"bills.paymentHistory",billId:id,payment:{...p}}}),transactionType:"payment",transactionDate:String(p.date).slice(0,10),amountMinor:money(p.amount),currency:"USD",accountId:billAccountId,description:"Payment: "+String(b.title??"Bill"),eventId:evId});billPaymentEvents.push({...base(evId,"event",p.date,p.date,{legacy:{source:"bills.paymentHistory",billId:id,payment:{...p}}}),eventType:"payment",title:"Payment: "+String(b.title??"Bill"),description:String(b.payee??""),status:"completed",occurredAt:iso(p.date,created),financialTransactionIds:[txId],source:"Full Life Control FLC-v5"});}
 }
 const relationships:Relationship[]=[];
 for(const link of (s.eventLinks??[]) as R[]){const fromMap:Record<string,string>={events:"event",loops:"open_loop",projects:"project",vehicles:"vehicle"};const toMap=fromMap;const fromId=String(link.fromId),toId=String(link.toId);const fromType=fromMap[link.fromType],toType=toMap[link.toType];if(fromType&&toType)relationships.push({...base(String(link.id),"relationship",link.createdAt,link.createdAt,{legacy:{source:"eventLinks",record:{...link}}}),fromId,fromType,toId,toType,relationshipType:relationType(link.relation),validFrom:String(link.createdAt??created).slice(0,10)});}
 for(const p of projects)if(p.metadata?.vehicleId){relationships.push({...base("project-vehicle-"+p.id,"relationship",p.createdAt,p.updatedAt,{legacy:{source:"projects.vehicleId"}}),fromId:p.id,fromType:"project",toId:String(p.metadata.vehicleId),toType:"vehicle",relationshipType:"uses"});}
 const entities:any[]=[];
 for(const x of (s.inventory??[]) as R[])entities.push({...base("inventory-"+String(x.id),"entity",x.createdAt,x.updatedAt,{legacy:{source:"inventory",record:{...x}}}),metadata:{legacyType:"inventory",...x}});
 for(const x of (s.insights??[]) as R[])entities.push({...base("insight-"+String(x.id),"entity",x.createdAt,x.updatedAt,{legacy:{source:"insights",record:{...x}}}),metadata:{legacyType:"insight",...x}});
 const allTyped:any[]=[...events,...people,...assets,...accounts,...transactions,...vehicles,...maintenance,...projects,...goals,...openLoops,...decisions,...documents,...recurringRules,...billEvents,...billLoops,...billPaymentEvents,...entities];
 const auditEntries:any[]=allTyped.concat(relationships).map(x=>({...base("audit-seed-"+x.entityType+"-"+String(x.id),"audit",x.createdAt,x.updatedAt,{seedVersion:IMMUTABLE_SEED_VERSION}),action:"create",targetId:String(x.id),targetType:x.entityType,timestamp:x.createdAt,after:{...x},source:"immutable-seed:FLC-v5"}));
 const db:LifeOSDatabase={
  schemaVersion:SCHEMA_VERSION,seedVersion:IMMUTABLE_SEED_VERSION,appVersion:APP_VERSION,
  entities,relationships,events:events.concat(billEvents,billPaymentEvents),openLoops:openLoops.concat(billLoops),people,assets,accounts,transactions,loans:[],loanPayments:[],vehicles,vehicleMaintenance:maintenance,properties:[],rooms:[],homeSystems:[],electricalDevices:[],projects,goals,decisions,documents,recurringRules,auditEntries,
  metadata:{databaseId:"lifeos-f8c4d3d9-immutable-seed",schemaVersion:SCHEMA_VERSION,seedVersion:IMMUTABLE_SEED_VERSION,appVersion:APP_VERSION,createdAt:created,updatedAt:created,metadataVersion:"FLC-v5",legacySeedSha256:"d22e0386087b4d6eeee4063d4d77eab29b17b6d675f0a92dc87c2bd5d546531b7",legacySeedFormat:s._format,legacyArchitecture:s._architecture,legacyExportedAt:s._exportedAt,legacySource:s}
 };
 return {format:"lifeos-backup",formatVersion:"1.0",schemaVersion:SCHEMA_VERSION,seedVersion:IMMUTABLE_SEED_VERSION,appVersion:APP_VERSION,exportedAt:created,checksum:"d22e0386087b4d6e9",database:db};
}

export function validateLegacySeedSource(source:unknown):boolean{
 const s=source as R; return !!s&&typeof s==="object"&&s._format==="FLC-v5"&&s._architecture==="LifeOS Core: Events + Graph + Resolver-owned Views"&&Array.isArray(s.events)&&Array.isArray(s.people)&&Array.isArray(s.assets)&&Array.isArray(s.vehicles)&&Array.isArray(s.maintenance);
}
