export type ISODateTime=string;export type CalendarDate=string;export type CurrencyCode="USD"|string;
export type AttentionState="none"|"due_today"|"due_soon"|"overdue"|"waiting"|"blocked"|"needs_decision"|"at_risk"|"unresolved";
export interface BaseEntity{id:string;entityType:string;createdAt:ISODateTime;updatedAt:ISODateTime;archivedAt?:ISODateTime;metadata?:Record<string,unknown>}
export type EventStatus="planned"|"scheduled"|"in_progress"|"completed"|"cancelled"|"skipped"|"failed";
export type EventType="task"|"meeting"|"conversation"|"appointment"|"purchase"|"payment"|"income"|"expense"|"transfer"|"maintenance"|"repair"|"inspection"|"travel"|"decision"|"observation"|"milestone"|"document"|"communication"|"workout"|"learning"|"other";
export interface Event extends BaseEntity{entityType:"event";eventType:EventType;title:string;description?:string;status:EventStatus;attention?:AttentionState;occurredAt?:ISODateTime;startAt?:ISODateTime;endAt?:ISODateTime;dueAt?:ISODateTime;completedAt?:ISODateTime;personIds?:string[];assetIds?:string[];projectIds?:string[];goalIds?:string[];openLoopIds?:string[];decisionIds?:string[];financialTransactionIds?:string[];documentIds?:string[]}
export interface OpenLoop extends BaseEntity{entityType:"open_loop";title:string;description?:string;type:"task"|"question"|"follow_up"|"waiting"|"decision"|"risk"|"commitment"|"other";status:"open"|"in_progress"|"waiting"|"blocked"|"resolved"|"cancelled";priority?:"low"|"normal"|"high"|"critical";dueAt?:ISODateTime}
export interface FinancialAccount extends BaseEntity{entityType:"financial_account";name:string;institution?:string;accountType:"checking"|"savings"|"cash"|"credit_card"|"loan"|"investment"|"other";currency:CurrencyCode;openingBalanceMinor?:number}
export interface Loan extends BaseEntity{entityType:"loan";provider:string;loanType:"installment"|"credit"|"mortgage"|"auto"|"personal"|"other";name:string;merchant?:string;originalPrincipalMinor:number;currency:CurrencyCode;aprBasisPoints?:number;scheduledPaymentMinor?:number;paymentFrequency?:"weekly"|"biweekly"|"monthly"|"quarterly"|"other";remainingPayments?:number;linkedAccountId?:string;status:"active"|"paid_off"|"defaulted"|"cancelled"|"closed"}
export interface Person extends BaseEntity{entityType:"person";displayName:string;firstName?:string;lastName?:string;email?:string[];phone?:string[]}
export interface Vehicle extends BaseEntity{entityType:"vehicle";make:string;model:string;year?:number;vin?:string;currentMileage?:number;mileageUnit:"mi"|"km";status:"owned"|"sold"|"inactive"|"disposed"}
export interface Property extends BaseEntity{entityType:"property";name:string;propertyType:"house"|"condo"|"apartment"|"land"|"other";status:"owned"|"sold"|"rented"|"inactive"}
export interface LifeOSDatabase{schemaVersion:string;seedVersion:string;appVersion:string;entities:BaseEntity[];relationships:BaseEntity[];events:Event[];openLoops:OpenLoop[];people:Person[];assets:BaseEntity[];accounts:FinancialAccount[];transactions:BaseEntity[];loans:Loan[];loanPayments:BaseEntity[];vehicles:Vehicle[];vehicleMaintenance:BaseEntity[];properties:Property[];rooms:BaseEntity[];homeSystems:BaseEntity[];electricalDevices:BaseEntity[];projects:BaseEntity[];goals:BaseEntity[];decisions:BaseEntity[];documents:BaseEntity[];recurringRules:BaseEntity[];auditEntries:BaseEntity[];metadata:{databaseId:string;schemaVersion:string;seedVersion:string;appVersion:string;createdAt:ISODateTime;updatedAt:ISODateTime}}