export type ISODateTime = string;
export type CalendarDate = string;
export type CurrencyCode = string;
export type AttentionState = "none"|"due_today"|"due_soon"|"overdue"|"waiting"|"blocked"|"needs_decision"|"at_risk"|"unresolved";
export interface BaseEntity { id:string; entityType:string; createdAt:ISODateTime; updatedAt:ISODateTime; createdBy?:string; updatedBy?:string; archivedAt?:ISODateTime; metadata?:Record<string,unknown> }
export type EventStatus="planned"|"scheduled"|"in_progress"|"completed"|"cancelled"|"skipped"|"failed";
export type EventType="task"|"meeting"|"conversation"|"appointment"|"purchase"|"payment"|"income"|"expense"|"transfer"|"maintenance"|"repair"|"inspection"|"travel"|"decision"|"observation"|"milestone"|"document"|"communication"|"workout"|"learning"|"other";
export interface Event extends BaseEntity { entityType:"event"; eventType:EventType; title:string; description?:string; status:EventStatus; attention?:AttentionState; occurredAt?:ISODateTime; startAt?:ISODateTime; endAt?:ISODateTime; dueAt?:ISODateTime; completedAt?:ISODateTime; source?:string; personIds?:string[]; assetIds?:string[]; projectIds?:string[]; goalIds?:string[]; openLoopIds?:string[]; decisionIds?:string[]; financialTransactionIds?:string[]; documentIds?:string[] }
export interface Relationship extends BaseEntity { entityType:"relationship"; fromId:string; fromType:string; toId:string; toType:string; relationshipType:RelationshipType; validFrom?:CalendarDate; validTo?:CalendarDate; metadata?:Record<string,unknown> }
export type RelationshipType="related_to"|"person_for"|"owns"|"uses"|"belongs_to"|"part_of"|"located_in"|"supports"|"depends_on"|"created_by"|"assigned_to"|"linked_to"|"caused_by"|"documents"|"scheduled_for"|"paid_by"|"payment_for"|"maintenance_for"|"child_of"|"parent_of"|"member_of";
export interface Person extends BaseEntity { entityType:"person"; firstName:string; middleName?:string; lastName?:string; displayName:string; email?:string[]; phone?:string[]; organization?:string; notes?:string; relationshipIds?:string[] }
export interface Asset extends BaseEntity { entityType:"asset"; assetType:"cash"|"investment"|"vehicle"|"property"|"equipment"|"skill"|"document"|"other"; name:string; description?:string; acquisitionDate?:CalendarDate; acquisitionCostMinor?:number; currency?:CurrencyCode; status?:"active"|"sold"|"retired"|"lost"|"archived" }
export interface FinancialAccount extends BaseEntity { entityType:"financial_account"; name:string; institution?:string; accountType:"checking"|"savings"|"cash"|"credit_card"|"loan"|"investment"|"other"; currency:CurrencyCode; openingBalanceMinor?:number; closedAt?:CalendarDate }
export interface FinancialTransaction extends BaseEntity { entityType:"financial_transaction"; transactionType:"income"|"expense"|"transfer"|"payment"|"refund"|"adjustment"; transactionDate:CalendarDate; amountMinor:number; currency:CurrencyCode; accountId:string; counterpartyAccountId?:string; merchant?:string; description?:string; categoryId?:string; loanId?:string; vehicleId?:string; propertyId?:string; eventId?:string; documentIds?:string[]; externalReference?:string }
export interface Loan extends BaseEntity { entityType:"loan"; provider:string; loanType:"installment"|"credit"|"mortgage"|"auto"|"personal"|"other"; name:string; merchant?:string; purchaseDescription?:string; originalPrincipalMinor:number; currency:CurrencyCode; aprBasisPoints?:number; originationDate?:CalendarDate; firstPaymentDate?:CalendarDate; scheduledPaymentMinor?:number; paymentFrequency?:"weekly"|"biweekly"|"monthly"|"quarterly"|"other"; totalPayments?:number; remainingPayments?:number; linkedAccountId?:string; status:"active"|"paid_off"|"defaulted"|"cancelled"|"closed" }
export interface LoanPayment extends BaseEntity { entityType:"loan_payment"; loanId:string; transactionId?:string; scheduledDate:CalendarDate; paidDate?:CalendarDate; scheduledAmountMinor:number; paidAmountMinor?:number; principalMinor?:number; interestMinor?:number; feeMinor?:number; status:"scheduled"|"paid"|"partial"|"missed"|"cancelled" }
export interface Vehicle extends BaseEntity { entityType:"vehicle"; assetId?:string; year?:number; make:string; model:string; trim?:string; vin?:string; licensePlate?:string; purchaseDate?:CalendarDate; purchasePriceMinor?:number; currentMileage?:number; mileageUnit:"mi"|"km"; status:"owned"|"sold"|"inactive"|"disposed" }
export interface VehicleMaintenance extends BaseEntity { entityType:"vehicle_maintenance"; vehicleId:string; eventId?:string; date:CalendarDate; mileage?:number; serviceType:string; description?:string; vendor?:string; costMinor?:number; currency?:CurrencyCode; partIds?:string[]; nextDueDate?:CalendarDate; nextDueMileage?:number; documentIds?:string[] }
export interface Property extends BaseEntity { entityType:"property"; assetId?:string; name:string; propertyType:"house"|"condo"|"apartment"|"land"|"other"; address?:{line1?:string;line2?:string;city?:string;state?:string;postalCode?:string;country?:string}; acquisitionDate?:CalendarDate; acquisitionCostMinor?:number; status:"owned"|"sold"|"rented"|"inactive" }
export interface Room extends BaseEntity { entityType:"room"; propertyId:string; name:string; roomType?:string; floor?:string; notes?:string }
export interface HomeSystem extends BaseEntity { entityType:"home_system"; propertyId:string; systemType:"electrical"|"plumbing"|"hvac"|"roof"|"security"|"appliance"|"other"; name:string; manufacturer?:string; model?:string; serialNumber?:string; installedDate?:CalendarDate; warrantyExpiration?:CalendarDate; notes?:string }
export interface ElectricalDevice extends BaseEntity { entityType:"electrical_device"; propertyId:string; roomId?:string; deviceType:"panel"|"breaker"|"circuit"|"outlet"|"switch"|"fixture"|"other"; name:string; circuitId?:string; panelId?:string; location?:string; controlsDeviceIds?:string[]; notes?:string }
export interface OpenLoop extends BaseEntity { entityType:"open_loop"; title:string; description?:string; type:"task"|"question"|"follow_up"|"waiting"|"decision"|"risk"|"commitment"|"other"; status:"open"|"in_progress"|"waiting"|"blocked"|"resolved"|"cancelled"; priority?:"low"|"normal"|"high"|"critical"; dueAt?:ISODateTime; waitingOnPersonId?:string; ownerPersonId?:string; relatedEventIds?:string[]; relatedProjectIds?:string[]; relatedDecisionIds?:string[]; resolvedAt?:ISODateTime }
export interface Project extends BaseEntity { entityType:"project"; name:string; description?:string; status:"planned"|"active"|"paused"|"completed"|"cancelled"; startDate?:CalendarDate; targetDate?:CalendarDate; ownerPersonId?:string }
export interface Goal extends BaseEntity { entityType:"goal"; name:string; description?:string; level:"annual"|"quarterly"|"monthly"|"weekly"; status:"planned"|"active"|"completed"|"cancelled"; parentGoalId?:string; targetDate?:CalendarDate; targetValue?:number; currentValue?:number; unit?:string }
export interface Decision extends BaseEntity { entityType:"decision"; question:string; context?:string; options?:DecisionOption[]; selectedOptionId?:string; decidedAt?:CalendarDate; reviewDate?:CalendarDate; personIds?:string[]; eventIds?:string[]; projectIds?:string[]; outcome?:string }
export interface DecisionOption { id:string; label:string; description?:string; evidence?:string[] }
export type AttachmentEntityType="event"|"person"|"asset"|"vehicle"|"property"|"project"|"goal"|"open_loop"|"document"|"maintenance"|"financial_transaction"|"loan"|"other";
export interface AttachmentLink { entityId:string; entityType:AttachmentEntityType; relationship?:string }
export interface Attachment extends BaseEntity { entityType:"attachment"; name:string; mimeType?:string; sizeBytes?:number; storageProvider:"external-url"|"browser-session"|"cloudflare-r2"|"icloud"|"other"; storageReference?:string; thumbnailUrl?:string; checksum?:string; documentType?:"manual"|"service_record"|"receipt"|"contract"|"statement"|"insurance"|"warranty"|"plan"|"photo"|"other"; description?:string; tags?:string[]; linkedEntities:AttachmentLink[] }
export interface Document extends BaseEntity { entityType:"document"; name:string; documentType?:"receipt"|"contract"|"statement"|"insurance"|"warranty"|"manual"|"plan"|"photo"|"other"; mimeType?:string; storageReference?:string; checksum?:string; documentDate?:CalendarDate }
export interface RecurringRule extends BaseEntity { entityType:"recurring_rule"; name:string; eventType:EventType; frequency:"daily"|"weekly"|"biweekly"|"monthly"|"quarterly"|"yearly"|"custom"; interval?:number; startDate:CalendarDate; endDate?:CalendarDate; nextOccurrence?:CalendarDate; enabled:boolean; template:Record<string,unknown> }
export interface AuditEntry extends BaseEntity { entityType:"audit"; action:"create"|"update"|"delete"|"import"|"export"|"restore"|"migrate"; targetId:string; targetType:string; timestamp:ISODateTime; before?:Record<string,unknown>; after?:Record<string,unknown>; source?:string }
export interface LifeOSDatabase { schemaVersion:string; seedVersion:string; appVersion:string; entities:BaseEntity[]; relationships:Relationship[]; events:Event[]; openLoops:OpenLoop[]; people:Person[]; assets:Asset[]; accounts:FinancialAccount[]; transactions:FinancialTransaction[]; loans:Loan[]; loanPayments:LoanPayment[]; vehicles:Vehicle[]; vehicleMaintenance:VehicleMaintenance[]; properties:Property[]; rooms:Room[]; homeSystems:HomeSystem[]; electricalDevices:ElectricalDevice[]; projects:Project[]; goals:Goal[]; decisions:Decision[]; documents:Document[]; recurringRules:RecurringRule[]; auditEntries:AuditEntry[]; attachments?:Attachment[]; metadata:DatabaseMetadata }
export interface DatabaseMetadata { databaseId:string; schemaVersion:string; seedVersion:string; appVersion:string; createdAt:ISODateTime; updatedAt:ISODateTime; lastBackupAt?:ISODateTime; lastRestoreAt?:ISODateTime; lastMigrationAt?:ISODateTime; seedSource?:{format?:string;architecture?:string;sha256?:string;exportedAt?:ISODateTime;legacySource?:Record<string,unknown>} }
export interface LifeOSBackup { format:"lifeos-backup"; formatVersion:string; schemaVersion:string; seedVersion:string; appVersion:string; exportedAt:ISODateTime; checksum?:string; database:LifeOSDatabase }
export interface AttentionItem { id:string; sourceType:string; sourceId:string; title:string; attention:AttentionState; dueAt?:ISODateTime; priority?:number; context?:Record<string,unknown> }
export const COLLECTIONS = ["entities","relationships","events","openLoops","people","assets","accounts","transactions","loans","loanPayments","vehicles","vehicleMaintenance","properties","rooms","homeSystems","electricalDevices","projects","goals","decisions","documents","recurringRules","auditEntries"] as const;
export type CollectionName = typeof COLLECTIONS[number];
