"use client";
import {useRef,useState} from "react";
import type {LifeOSBackup,LifeOSDatabase,CollectionName} from "@/domain/contracts/database";
import {importSeed,restoreBackup,validateLifeOSBackup,validateSeedBackup,explainSeedValidation,explainBackupValidation,validateSeedContinuity} from "@/domain/services/seed";
import {validateDatabaseIntegrity} from "@/domain/resolvers/integrity";
import {getBundledImmutableSeed} from "@/domain/services/bundled-seed";

type Props={db:LifeOSDatabase;onPersist:(db:LifeOSDatabase,message:string)=>Promise<void>|void;onNotice:(message:string)=>void};

const collections=["events","openLoops","people","assets","accounts","transactions","loans","loanPayments","vehicles","vehicleMaintenance","properties","rooms","homeSystems","electricalDevices","projects","goals","decisions","documents","recurringRules","relationships","auditEntries"] as const;

function makeBackup(db:LifeOSDatabase):LifeOSBackup{return{format:"lifeos-backup",formatVersion:"1.0",schemaVersion:db.schemaVersion,seedVersion:db.seedVersion,appVersion:db.appVersion,exportedAt:new Date().toISOString(),database:db}}

function download(content:string,filename:string,type="application/json"){const blob=new Blob([content],{type});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function csvCell(value:unknown){if(value==null)return "";const text=typeof value==="string"?value:JSON.stringify(value);return JSON.stringify(text)}
function collectionCsv(db:LifeOSDatabase,name:CollectionName){const rows=(db[name] as unknown as Record<string,unknown>[]);const keys=Array.from(new Set(rows.flatMap(r=>Object.keys(r))));return [keys.map(csvCell).join(","),...rows.map(r=>keys.map(k=>csvCell(r[k])).join(","))].join("\n")}

export default function DataControlCenter({db,onPersist,onNotice}:Props){
 const inputRef=useRef<HTMLInputElement>(null); const seedRef=useRef<HTMLInputElement>(null);
 const [mode,setMode]=useState<"import"|"export"|"integrity"|"seed"|"audit">("import");
 const [preview,setPreview]=useState<LifeOSDatabase|null>(null); const [previewKind,setPreviewKind]=useState<"restore"|"seed"|null>(null); const [fileName,setFileName]=useState("");
 const integrity=validateDatabaseIntegrity(db);
 const totalRecords=collections.reduce((n,k)=>n+(db[k] as unknown[]).length,0);
 const auditCount=db.auditEntries.length;
 function exportFull(){download(JSON.stringify(makeBackup(db),null,2),"lifeos-backup.json");onNotice("Full LifeOS backup exported.")}
 function exportDatabase(){download(JSON.stringify(db,null,2),"lifeos-database.json");onNotice("Human-readable database export created.")}
 function exportCsv(name:CollectionName){download(collectionCsv(db,name),`lifeos-${name}.csv`,"text/csv");onNotice(`${name} CSV exported.`)}
 function readFile(file:File,kind:"restore"|"seed"){file.text().then(raw=>{let parsed:unknown;try{parsed=JSON.parse(raw)}catch{onNotice("Import rejected: invalid JSON.");return}if(kind==="seed"){if(!validateSeedBackup(parsed)){onNotice("Seed rejected: "+explainSeedValidation(parsed).reason);return}}else if(!validateLifeOSBackup(parsed)){onNotice("Restore rejected: "+explainBackupValidation(parsed).reason);return}const candidate=kind==="seed"?importSeed(parsed):restoreBackup(parsed);const check=validateDatabaseIntegrity(candidate);if(!check.valid){onNotice("Import rejected: database integrity failed.");return}const continuity=validateSeedContinuity(db,candidate);if(!continuity.valid){onNotice((kind==="seed"?"Seed":"Restore")+" rejected: "+continuity.reason);return}setPreview(candidate);setPreviewKind(kind);setFileName(file.name);setMode("import");onNotice(`${kind==="seed"?"Seed":"Backup"} loaded for review. Nothing has changed yet.`)}).catch(()=>onNotice("Import rejected: unable to read file."))}
 async function commitPreview(){if(!preview||!previewKind)return;const current=structuredClone(db);try{const continuity=validateSeedContinuity(current,preview);if(!continuity.valid){onNotice("Commit rejected: "+continuity.reason);return}const check=validateDatabaseIntegrity(preview);if(!check.valid){onNotice("Commit rejected: database integrity failed.");return}if(previewKind==="restore"){download(JSON.stringify(makeBackup(current),null,2),`lifeos-pre-restore-${new Date().toISOString().replace(/[:.]/g,"-")}.json`)}await onPersist(structuredClone(preview),previewKind==="seed"?"Immutable seed imported and verified.":"Backup restored and verified.");setPreview(null);setPreviewKind(null);setFileName("")}catch{onNotice("Commit failed. Local database was not intentionally changed.")}}
 function installSeed(){const seed=getBundledImmutableSeed();const candidate=structuredClone(seed.database);const check=validateDatabaseIntegrity(candidate);const continuity=validateSeedContinuity(db,candidate);if(!check.valid){onNotice("Bundled seed rejected: integrity failure.");return}if(!continuity.valid){onNotice("Bundled seed rejected: "+continuity.reason);return}setPreview(candidate);setPreviewKind("seed");setFileName("Bundled immutable Full Life Control seed");onNotice("Bundled seed loaded for review. Nothing has changed yet.")}
 return <section className="data-control-center card">
  <div className="section-title"><div><div className="kicker">LifeOS / Data</div><h2>Data Control Center</h2><div className="row-meta">Controlled movement of the graph in and out of LifeOS.</div></div><span className="badge">{totalRecords} records</span></div>
  <div className="data-control-tabs"><button className={mode==="import"?"active":""} onClick={()=>setMode("import")}>Import</button><button className={mode==="export"?"active":""} onClick={()=>setMode("export")}>Export</button><button className={mode==="integrity"?"active":""} onClick={()=>setMode("integrity")}>Integrity</button><button className={mode==="seed"?"active":""} onClick={()=>setMode("seed")}>Seed</button><button className={mode==="audit"?"active":""} onClick={()=>setMode("audit")}>Audit</button></div>
  {mode==="import"&&<div className="data-control-panel"><div className="data-control-grid"><button className="data-control-action" onClick={()=>inputRef.current?.click()}><strong>Restore LifeOS backup</strong><span>Load a validated .json backup and review it before commit.</span></button><button className="data-control-action" onClick={()=>seedRef.current?.click()}><strong>Import immutable seed</strong><span>Seed lineage must match the established baseline.</span></button><button className="data-control-action" onClick={installSeed}><strong>Load bundled seed</strong><span>Use the embedded Full Life Control seed without changing it.</span></button></div><input ref={inputRef} hidden type="file" accept=".json,application/json" onChange={e=>{const f=e.target.files?.[0];if(f)readFile(f,"restore");e.currentTarget.value=""}}/><input ref={seedRef} hidden type="file" accept=".json,application/json" onChange={e=>{const f=e.target.files?.[0];if(f)readFile(f,"seed");e.currentTarget.value=""}}/>{preview&&<div className="data-preview"><div className="section-title"><div><div className="kicker">Preview</div><h3>{fileName}</h3></div><span className="badge">{previewKind}</span></div><p className="row-meta">Candidate contains {collections.reduce((n,k)=>n+(preview[k] as unknown[]).length,0)} records. The current database has not been changed.</p><div className="data-preview-actions"><button className="action" onClick={()=>{setPreview(null);setPreviewKind(null)}}>Discard</button><button className="action primary" onClick={commitPreview}>Commit import</button></div></div>}</div>}
  {mode==="export"&&<div className="data-control-panel"><div className="data-control-grid"><button className="data-control-action" onClick={exportFull}><strong>Full LifeOS backup</strong><span>Portable, versioned backup including schema and seed lineage.</span></button><button className="data-control-action" onClick={exportDatabase}><strong>Human-readable JSON</strong><span>Database-only export for inspection or transformation.</span></button></div><div className="data-export-list"><div className="kicker">Domain CSV exports</div><div className="data-csv-grid">{collections.map(k=><button key={k} className="mini-action" onClick={()=>exportCsv(k)}>{k}</button>)}</div></div></div>}
  {mode==="integrity"&&<div className="data-control-panel"><div className={integrity.valid?"integrity-ok":"integrity-fail"}><strong>{integrity.valid?"✓ Database integrity valid":"⚠ Integrity errors detected"}</strong><span>{integrity.errors?.length??0} error(s)</span></div><div className="row-meta">Schema {db.schemaVersion} · Seed {db.seedVersion} · App {db.appVersion}</div>{integrity.errors?.length?<div className="data-integrity-list">{integrity.errors.slice(0,20).map((e,i)=><div className="row" key={i}>{e.message}</div>)}</div>:<div className="row-meta">All indexed collections passed the current integrity resolver.</div>}</div>}
  {mode==="seed"&&<div className="data-control-panel"><div className="data-seed-card"><div><div className="kicker">Immutable baseline</div><h3>Full Life Control</h3><div className="row-meta">Current seed version: {db.seedVersion}</div></div><button className="action primary" onClick={installSeed}>Review bundled seed</button></div><p className="row-meta">The seed is never silently replaced by ordinary imports. Seed lineage is checked before any candidate can be committed.</p></div>}
  {mode==="audit"&&<div className="data-control-panel"><div className="section-title"><h3>Audit trail</h3><span className="badge">{auditCount}</span></div><div className="list">{db.auditEntries.slice().sort((a,b)=>b.timestamp.localeCompare(a.timestamp)).slice(0,30).map(a=><div className="row" key={a.id}><div className="row-main"><div className="row-title">{a.action} · {a.targetType}</div><div className="row-meta">{a.timestamp} · {a.targetId}</div></div></div>)}</div>{!auditCount&&<div className="row-meta">No audit entries recorded yet.</div>}</div>}
 </section>;
}
