"use client";
import {useMemo,useState} from "react";
import {SCION_XB_TROUBLESHOOTING,type GarageTroubleshootingPath} from "@/domain/data/garage-troubleshooting";

export default function GarageTroubleshooting(){
 const [query,setQuery]=useState("");const [selectedId,setSelectedId]=useState(SCION_XB_TROUBLESHOOTING[0]?.id??"");
 const matches=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return SCION_XB_TROUBLESHOOTING;return SCION_XB_TROUBLESHOOTING.filter(p=>[p.symptom,p.system,...p.triggers,...p.likelyCauses].join(" ").toLowerCase().includes(q));},[query]);
 const selected=matches.find(p=>p.id===selectedId)??matches[0];
 const select=(p:GarageTroubleshootingPath)=>setSelectedId(p.id);
 return <section className="garage-troubleshooting"><div className="garage-troubleshooting-head"><div><div className="kicker">Factory Diagnostic Guide</div><h3>Symptom → Diagnostic Path</h3><p className="row-meta">2006 Scion xB · 1NZ-FE · factory repair-manual references</p></div><span className="badge">{SCION_XB_TROUBLESHOOTING.length}</span></div><input className="command-input garage-troubleshooting-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search symptoms, causes, systems…" aria-label="Search factory troubleshooting guide"/><div className="garage-troubleshooting-layout"><div className="garage-troubleshooting-list" role="listbox" aria-label="Troubleshooting symptoms">{matches.map(p=><button type="button" key={p.id} className={"garage-troubleshooting-item "+(selected?.id===p.id?"active":"")} onClick={()=>select(p)}><span className="garage-troubleshooting-system">{p.system}</span><strong>{p.symptom}</strong><span>{p.likelyCauses.slice(0,2).join(" · ")}</span></button>)}{!matches.length&&<div className="row-meta">No factory troubleshooting path matches that search.</div>}</div>{selected&&<div className="garage-troubleshooting-detail"><div className="kicker">{selected.system}</div><h4>{selected.symptom}</h4><div className="garage-troubleshooting-grid"><div className="garage-troubleshooting-block"><div className="field-label">Likely / suspected areas</div><ol>{selected.likelyCauses.map((x,i)=><li key={i}>{x}</li>)}</ol></div><div className="garage-troubleshooting-block"><div className="field-label">Factory diagnostic sequence</div><ol>{selected.sequence.map((x,i)=><li key={i}>{x}</li>)}</ol></div></div><div className="garage-troubleshooting-block"><div className="field-label">Required measurements / specifications</div><div className="garage-spec-list">{selected.measurements.map((x,i)=><div className="garage-spec" key={i}>{x}</div>)}</div></div><div className="garage-troubleshooting-block"><div className="field-label">Relevant manual sections</div><div className="garage-chip-list">{selected.sections.map((x,i)=><span className="garage-chip" key={i}>{x.section} · {x.ref}</span>)}</div></div><div className="garage-troubleshooting-block"><div className="field-label">Garage context</div><div className="garage-chip-list">{selected.garageLinks.map((x,i)=><span className="garage-chip" key={i}>{x}</span>)}</div></div></div>}</div></section>;
}