"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import type {ReactNode} from "react";
import type {LifeOSBackup} from "@/domain/contracts/database";
import {createEmptyDatabase} from "@/domain/services/empty-database";
import {importSeed,validateSeedBackup,explainSeedValidation} from "@/domain/services/seed";
import {validateDatabase} from "@/domain/services/integrity";
import {resolveMissionControl} from "@/domain/resolvers/mission-control";
import {resolveSearch} from "@/domain/resolvers/search";
import {resolveGraph} from "@/domain/resolvers/graph";
import {loadLocalDatabase,saveLocalDatabase} from "@/storage/indexeddb/database";
import {createEvent,createOpenLoop,updateEventStatus,updateOpenLoopStatus} from "@/domain/services/operations";
import {resolveFinancialHealth} from "@/domain/resolvers/financial-health";

export default function MissionControl(){
 const [db,setDb]=useState(createEmptyDatabase); const [query,setQuery]=useState(""); const [notice,setNotice]=useState(""); const [activeView,setActiveView]=useState("mission"); const [command,setCommand]=useState<"event"|"loop"|null>(null);
 const fileRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{loadLocalDatabase().then(local=>{if(local)setDb(local);else saveLocalDatabase(createEmptyDatabase())}).catch(()=>setNotice("Local database could not be opened."))},[]);
 const vm=useMemo(()=>resolveMissionControl(db),[db]); const financialHealth=useMemo(()=>resolveFinancialHealth(db),[db]); const results=useMemo(()=>resolveSearch(db,query),[db,query]);
 const graph=useMemo(()=>{const id=db.events[0]?.id??db.openLoops[0]?.id??db.accounts[0]?.id;return id?resolveGraph(db,id):null},[db]);
 const issues=useMemo(()=>validateDatabase(db),[db]);
function persist(next:typeof db,message:string){setDb(next);saveLocalDatabase(next).then(()=>setNotice(message)).catch(()=>setNotice("Change created in memory but could not be saved."))}
 function addEvent(title:string){persist(createEvent(db,{title,eventType:"task",status:"planned"}),"Event added to the graph.")}
 function addLoop(title:string){persist(createOpenLoop(db,{title,type:"task",status:"open",priority:"normal"}),"Open loop added to the graph.")}
 function completeEvent(id:string){persist(updateEventStatus(db,id,"completed"),"Event completed.")}
 function resolveLoop(id:string){persist(updateOpenLoopStatus(db,id,"resolved"),"Open loop resolved.")}
 function exportBackup(){const backup:LifeOSBackup={format:"lifeos-backup",formatVersion:"1.0",schemaVersion:db.schemaVersion,seedVersion:db.seedVersion,appVersion:db.appVersion,exportedAt:new Date().toISOString(),database:db};const blob=new Blob([JSON.stringify(backup,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="lifeos-backup.json";a.click();URL.revokeObjectURL(url);}
 function importFile(file:File){file.text().then(raw=>{const parsed:unknown=JSON.parse(raw);if(!validateSeedBackup(parsed)){setNotice("Import rejected: "+explainSeedValidation(parsed).reason);return;}const imported=importSeed(parsed);const validation=validateDatabase(imported);if(validation.some(x=>x.severity==="error")){setNotice("Import rejected: database integrity errors found.");return;}saveLocalDatabase(imported).then(()=>{setDb(imported);setNotice("Immutable seed loaded and validated.")}).catch(()=>setNotice("Seed validated but could not be saved locally."));}).catch(()=>setNotice("Import rejected: invalid JSON."));}
 return <div className="lifeos-shell">
  <header className="topbar"><div className="topbar-inner"><div className="brand">LIFE<span>OS</span> V2</div><input className="search" aria-label="Universal search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search the graph…" /><div className="status-pill">LOCAL-FIRST</div></div></header>
  <main className="content">
   <section className="hero"><div className="kicker">Mission Control</div><h1>Attention first.</h1><p className="subtitle">LifeOS turns the graph into an operating system: capture work, act on attention, close loops, and preserve every action as history.</p><div className="command-bar"><button className="action primary" onClick={()=>setCommand("event")}>＋ Event</button><button className="action" onClick={()=>setCommand("loop")}>＋ Open Loop</button></div></section>
   {notice&&<div className="notice">{notice}</div>}
   {query&&<section className="card search-results"><div className="section-title"><h2>Graph Search</h2><span className="badge">{results.length}</span></div>{results.length?results.map(x=><div className="row" key={x.sourceType+x.id}><div className="row-main"><div className="row-title">{x.title}</div><div className="row-meta">{x.sourceType} · {x.subtitle}</div></div></div>):<Empty text="No graph matches."/ >}</section>}
   <section className="grid metrics"><Metric label="Attention" value={String(vm.attention.length)} accent/><Metric label="Open loops" value={String(vm.openLoops.length)}/><Metric label="Relationships" value={String(db.relationships.length)}/><Metric label="Events" value={String(db.events.length)}/></section>
   <section className="grid metrics secondary-metrics"><Metric label="Accounts" value={String(db.accounts.length)}/><Metric label="Loans" value={String(db.loans.length)}/><Metric label="Vehicles" value={String(db.vehicles.length)}/><Metric label="Properties" value={String(db.properties.length)}/></section>
   {activeView==="mission"&&<> style={{marginTop:14}}><Panel title="Attention" badge={vm.attention.length}><div className="list">{vm.attention.length?vm.attention.map(item=><div className="row" key={item.id}><div className="row-main"><div className="row-title">{item.title}</div><div className="row-meta">{item.sourceType.replace("_"," ")} · {item.dueAt?new Date(item.dueAt).toLocaleDateString():"No date"}</div></div><div className="row-actions"><div className={"attention "+(item.attention==="overdue"?"overdue":item.attention==="blocked"?"blocked":"")}>{item.attention.replace("_"," ")}</div>{item.sourceType==="event"&&<button className="mini-action" onClick={()=>completeEvent(item.sourceId)}>Done</button>}{item.sourceType==="open_loop"&&<button className="mini-action" onClick={()=>resolveLoop(item.sourceId)}>Resolve</button>}</div></div>):<Empty text="No attention items."/ >}</div></Panel>
   <Panel title="Open Loops" badge={vm.openLoops.length}><div className="list">{vm.openLoops.length?vm.openLoops.map(loop=><div className="row" key={loop.id}><div className="row-main"><div className="row-title">{loop.title}</div><div className="row-meta">{loop.priority??"normal"} · {loop.status}</div></div><button className="mini-action" onClick={()=>resolveLoop(loop.id)}>Resolve</button></div>):<Empty text="No open loops."/ >}</div></Panel></section>
   <section className="grid two" style={{marginTop:14}}><Panel title="Today"><div className="list">{vm.today.map(e=><div className="row" key={e.id}><div className="row-main"><div className="row-title">{e.title}</div><div className="row-meta">{e.eventType} · {e.status}</div></div></div>)}{!vm.today.length&&<Empty text="Nothing scheduled for today."/ >}</div></Panel>
   <Panel title="Graph Status"><div className="list"><StatusRow label="Canonical Events" value={String(db.events.length)} tag="SOURCE"/><StatusRow label="Relationships" value={String(db.relationships.length)} tag="GRAPH"/><StatusRow label="IndexedDB" value="Browser-local" tag="READY"/><StatusRow label="Seed" value={db.seedVersion} tag={db.seedVersion==="NO_REAL_SEED_LOADED"?"WAITING":"LOADED"}/><StatusRow label="Integrity" value={issues.length?"Issues found":"Valid"} tag={issues.length?"CHECK":"VALID"}/></div></Panel></section>
   <section className="card" style={{marginTop:14}}><div className="section-title"><h2>Graph Neighborhood</h2><span className="badge">{graph?.nodes.length??0} nodes</span></div>{graph?.nodes.length?<div className="graph-list">{graph.nodes.map(n=><div className="graph-node" key={n.id}><span className="graph-type">{n.type}</span><span>{n.label}</span></div>)}</div>:<Empty text="Relationships will appear here when the real seed or records are loaded."/ >}</section>
   <section className="card" style={{marginTop:14}}><div className="section-title"><h2>Recent Events</h2><span className="badge">{vm.recent.length}</span></div><div className="list">{vm.recent.map(e=><div className="row" key={e.id}><div className="row-main"><div className="row-title">{e.title}</div><div className="row-meta">{e.eventType} · {new Date(e.updatedAt).toLocaleString()}</div></div></div>)}{!vm.recent.length&&<Empty text="No events stored yet."/ >}</div></section>
   </>}
   {activeView==="finance"&&<section className="grid two" style={{marginTop:14}}>
    <Panel title="Financial Accounts" badge={db.accounts.length}><div className="list">{db.accounts.length?db.accounts.map(a=><div className="row" key={a.id}><div className="row-main"><div className="row-title">{a.name}</div><div className="row-meta">{a.accountType} · {a.institution??"Institution not set"} · {a.currency}</div></div></div>):<Empty text="No financial accounts loaded."/ >}</div></Panel>
    <Panel title="Loans & Payments" badge={db.loans.length}><div className="list"><StatusRow label="Scheduled debt" value={(financialHealth.scheduledDebtMinor/100).toLocaleString(undefined,{style:"currency",currency:"USD"})} tag="FORECAST"/><StatusRow label="Overdue payments" value={String(financialHealth.overduePayments)} tag={financialHealth.overduePayments?"ATTENTION":"CLEAR"}/><StatusRow label="Transactions" value={String(financialHealth.transactionCount)} tag="LEDGER"/>{db.loans.length?db.loans.map(l=><div className="row" key={l.id}><div className="row-main"><div className="row-title">{l.name}</div><div className="row-meta">{l.provider} · {l.status} · {l.scheduledPaymentMinor!=null?(l.scheduledPaymentMinor/100).toLocaleString(undefined,{style:"currency",currency:l.currency}):"Payment not set"}</div></div></div>):<Empty text="No loans loaded."/ >}</div><div className="section-title" style={{marginTop:12}}><span className="row-meta">Scheduled payments</span><span className="badge">{vm.finance.upcomingPayments}</span></div></Panel>
   </section>}
   {activeView==="assets"&&<section className="grid two" style={{marginTop:14}}>
    <Panel title="Vehicles" badge={db.vehicles.length}><div className="list">{db.vehicles.length?db.vehicles.map(v=><div className="row" key={v.id}><div className="row-main"><div className="row-title">{v.year??""} {v.make} {v.model}</div><div className="row-meta">{v.status} · {v.currentMileage!=null?v.currentMileage.toLocaleString()+" "+v.mileageUnit:"Mileage not set"}</div></div></div>):<Empty text="No vehicles loaded."/ >}</div></Panel>
    <Panel title="Properties" badge={db.properties.length}><div className="list">{db.properties.length?db.properties.map(p=><div className="row" key={p.id}><div className="row-main"><div className="row-title">{p.name}</div><div className="row-meta">{p.propertyType} · {p.status}</div></div></div>):<Empty text="No properties loaded."/ >}</div></Panel>
   </section>}
   {activeView==="events"&&<section className="card" style={{marginTop:14}}><div className="section-title"><h2>Event Stream</h2><span className="badge">{db.events.length}</span></div><div className="list">{db.events.length?[...db.events].sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).map(e=><div className="row" key={e.id}><div className="row-main"><div className="row-title">{e.title}</div><div className="row-meta">{e.eventType} · {e.status} · {e.startAt?new Date(e.startAt).toLocaleString():e.dueAt?new Date(e.dueAt).toLocaleString():"No scheduled time"}</div></div>{e.status!=="completed"&&<button className="mini-action" onClick={()=>completeEvent(e.id)}>Done</button>}</div>):<Empty text="No canonical events stored yet."/ >}</div></section>}
   {activeView==="more"&&<section className="grid two" style={{marginTop:14}}>
    <Panel title="People & Relationships"><StatusRow label="People" value={String(db.people.length)} tag="GRAPH"/><StatusRow label="Relationships" value={String(db.relationships.length)} tag="GRAPH"/><StatusRow label="Projects" value={String(db.projects.length)} tag="GRAPH"/><StatusRow label="Goals" value={String(db.goals.length)} tag="GRAPH"/><StatusRow label="Decisions" value={String(db.decisions.length)} tag="GRAPH"/><StatusRow label="Documents" value={String(db.documents.length)} tag="GRAPH"/></Panel>
    <Panel title="System"><StatusRow label="Schema" value={db.schemaVersion} tag="CORE"/><StatusRow label="App" value={db.appVersion} tag="CORE"/><StatusRow label="Storage" value="IndexedDB" tag="LOCAL"/><StatusRow label="Seed" value={db.seedVersion} tag={db.seedVersion==="NO_REAL_SEED_LOADED"?"WAITING":"LOADED"}/></Panel>
   </section>}
   <section className="card tools-panel"><div><div className="section-title"><h2>Data Controls</h2></div><p className="row-meta">The real Full Life Control seed is protected. Imports are validated before they can replace the local graph.</p></div><div className="tool-actions"><button className="action" onClick={exportBackup}>Export backup</button><button className="action primary" onClick={()=>fileRef.current?.click()}>Load immutable seed</button><input ref={fileRef} hidden type="file" accept="application/json,.json" onChange={e=>{const file=e.target.files?.[0];if(file)importFile(file);e.currentTarget.value=""}} /></div></section>
  </main>
  {command&&<CommandModal type={command} onClose={()=>setCommand(null)} onEvent={addEvent} onLoop={addLoop}/>}<nav className="bottom-nav"><div className="nav-inner">{[["mission","⌂","Mission"],["events","◷","Events"],["finance","$","Finance"],["assets","◇","Assets"],["more","⋯","More"]].map(([id,icon,label])=><button key={id} onClick={()=>setActiveView(id)} className={"nav-button "+(activeView===id?"active":"")}><span className="nav-icon">{icon}</span>{label}</button>)}</div></nav>
 </div>
}
function Metric({label,value,accent}:{label:string;value:string;accent?:boolean}){return <div className="card"><div className="metric-label">{label}</div><div className={"metric-value "+(accent?"metric-accent":"")}>{value}</div></div>}
function Panel({title,badge,children}:{title:string;badge?:number;children:ReactNode}){return <section className="card"><div className="section-title"><h2>{title}</h2>{badge!==undefined&&<span className="badge">{badge}</span>}</div>{children}</section>}
function StatusRow({label,value,tag}:{label:string;value:string;tag:string}){return <div className="row"><div className="row-main"><div className="row-title">{label}</div><div className="row-meta">{value}</div></div><span className="badge">{tag}</span></div>}
function Empty({text}:{text:string}){return <div className="row"><div className="row-meta">{text}</div></div>}

function CommandModal({type,onClose,onEvent,onLoop}:{type:"event"|"loop";onClose:()=>void;onEvent:(title:string)=>void;onLoop:(title:string)=>void}){const [title,setTitle]=useState("");const submit=()=>{if(!title.trim())return;if(type==="event")onEvent(title.trim());else onLoop(title.trim());onClose()};return <div className="modal-backdrop" onMouseDown={onClose}><div className="command-modal" onMouseDown={e=>e.stopPropagation()}><div className="section-title"><h2>{type==="event"?"New Event":"New Open Loop"}</h2><button className="mini-action" onClick={onClose}>Close</button></div><input autoFocus className="command-input" value={title} onChange={e=>setTitle(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")submit()}} placeholder={type==="event"?"What happened or needs to happen?":"What remains open?"}/><button className="action primary full" onClick={submit}>Add to LifeOS</button></div></div>}
